### ISSUE TITLE
Linux crash

### ISSUE THREAD

**Issue by kimme** [gunstarpl/Civilization-5-Mods#1]
This MOD makes my Civ5 BNW crash. Selected with other MODS it crahes and selected as the only MOD it crashes.

I'm talking about the "Quiet Diplomacy" MOD

**Comment by doanamo** [comment]
Mods that replace the base game's DLL (like Quiet Diplomacy does) can only work with Windows version of Civ 5. AFAIK Linux platform is limited to XML/Lua way of modding. There's no way this particular mod could be rewritten to Lua. I tried doing that the first time I was implementing the mod and it's just not possible. Sorry!
